services:
  postgres:
    restart: always
    image: postgres:12.0-alpine
    ports:
      - "5432:5432"
    environment:
      - DEBUG=false
      - POSTGRES_DB=shop
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./modules/core/src/main/resources/database.sql:/docker-entrypoint-initdb.d/init.sql

  redis:
    restart: always
    image: redis:5.0.0
    ports:
      - "6379:6379"
    environment:
      - DEBUG=false

  ldap:
    restart: always
    image: osixia/openldap:1.5.0
    ports:
      - "389:389"
      - "636:636"
    environment:
      - LDAP_ORGANISATION=Shopping Cart
      - LDAP_DOMAIN=shoppingcart.local
      - LDAP_ADMIN_PASSWORD=admin
      - LDAP_CONFIG_PASSWORD=config